2020-07-15 12:56:54,506 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 178, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 170, in main
    logger.info("Reading config file: {}".format(args.config_file))
AttributeError: 'Namespace' object has no attribute 'config_file'
2020-07-15 12:57:37,300 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 178, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 170, in main
    logger.info("Reading config file: {}".format(args.config))
AttributeError: 'Namespace' object has no attribute 'config'
2020-07-15 12:58:41,747 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 178, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 170, in main
    logger.info("Reading config file: {}".format(args.config))
AttributeError: 'Namespace' object has no attribute 'config'
2020-07-15 13:01:10,998 __main__ INFO Reading config file: '../main.toml'
2020-07-15 13:01:10,998 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 178, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 171, in main
    config = load_config(args.config)
  File "/home/wessel/510/building_detection/neat_eo/core.py", line 36, in load_config
    config = toml.load(os.path.expanduser(path))
  File "/home/wessel/.local/lib/python3.6/site-packages/toml/decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:
FileNotFoundError: [Errno 2] No such file or directory: "'../main.toml'"
2020-07-15 13:04:17,828 __main__ INFO Reading config file: '~/510/building_detection/main.toml'
2020-07-15 13:04:17,828 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 178, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 171, in main
    config = load_config(args.config)
  File "/home/wessel/510/building_detection/neat_eo/core.py", line 36, in load_config
    config = toml.load(os.path.expanduser(path))
  File "/home/wessel/.local/lib/python3.6/site-packages/toml/decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:
FileNotFoundError: [Errno 2] No such file or directory: "'~/510/building_detection/main.toml'"
2020-07-15 13:05:32,316 __main__ INFO Reading config file: '../main.toml'
2020-07-15 13:05:32,316 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 178, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 171, in main
    config = load_config(args.config)
  File "/home/wessel/510/building_detection/neat_eo/core.py", line 36, in load_config
    config = toml.load(os.path.expanduser(path))
  File "/home/wessel/.local/lib/python3.6/site-packages/toml/decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:
FileNotFoundError: [Errno 2] No such file or directory: "'../main.toml'"
2020-07-15 13:06:20,150 __main__ INFO Reading config file: '../main.toml'
2020-07-15 13:06:20,150 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 178, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 171, in main
    config = load_config(args.config)
  File "/home/wessel/510/building_detection/neat_eo/core.py", line 37, in load_config
    config = toml.load(os.path.expanduser(path))
  File "/home/wessel/.local/lib/python3.6/site-packages/toml/decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:
FileNotFoundError: [Errno 2] No such file or directory: "'../main.toml'"
2020-07-15 13:07:14,598 __main__ INFO Reading config file: ../main.toml
2020-07-15 13:07:14,599 __main__ INFO Preprocessing
2020-07-15 13:07:14,599 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 178, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 175, in main
    preprocess(config)
TypeError: preprocess() takes 0 positional arguments but 1 was given
2020-07-15 13:08:04,503 __main__ INFO Reading config file: ../main.toml
2020-07-15 13:08:04,504 __main__ INFO Preprocessing
2020-07-15 13:08:04,664 __main__ INFO Creating label masks for pinery-bushfire
2020-07-15 13:08:04,669 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 178, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 175, in main
    preprocess(config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 131, in preprocess
    rasterizing(file, (1024, 1024), os.path.join(label_directory, file.split('_')[1] + '.png'), config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 61, in rasterizing
    out.putpalette(palette)
  File "/home/wessel/.local/lib/python3.6/site-packages/PIL/Image.py", line 1701, in putpalette
    data = bytes(data)
TypeError: 'list' object cannot be interpreted as an integer
2020-07-15 13:21:36,724 __main__ INFO Reading config file: ../main.toml
2020-07-15 13:21:36,725 __main__ INFO Preprocessing
2020-07-15 13:21:36,882 __main__ INFO Creating label masks for pinery-bushfire
2020-07-15 13:21:44,855 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 186, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 183, in main
    preprocess(config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 139, in preprocess
    rasterizing(file, (1024, 1024), os.path.join(label_directory, file.split('_')[1] + '.png'), config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 79, in rasterizing
    building = shapely.wkt.loads(row['wkt'])
  File "/home/wessel/.local/lib/python3.6/site-packages/pandas/core/series.py", line 871, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/wessel/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4379, in get_value
    s = extract_array(series, extract_numpy=True)
  File "/home/wessel/.local/lib/python3.6/site-packages/pandas/core/construction.py", line 383, in extract_array
    obj = obj.to_numpy()
  File "/home/wessel/.local/lib/python3.6/site-packages/pandas/core/arrays/numpy_.py", line 417, in to_numpy
    def to_numpy(self, dtype=None, copy=False, na_value=lib.no_default):
KeyboardInterrupt
2020-07-15 13:22:42,695 __main__ INFO Reading config file: ../main.toml
2020-07-15 13:22:42,696 __main__ INFO Preprocessing
2020-07-15 13:22:42,854 __main__ INFO Creating label masks for pinery-bushfire
2020-07-15 13:23:00,295 __main__ INFO Creating label masks for portugal-wildfire
2020-07-15 13:23:41,931 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 186, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 183, in main
    preprocess(config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 136, in preprocess
    shutil.copyfile(file, os.path.join(image_directory, file.split('_')[1] + '.png'))
  File "/home/wessel/anaconda3/envs/neateo/lib/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/home/wessel/anaconda3/envs/neateo/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
KeyboardInterrupt
2020-07-15 13:26:09,997 __main__ INFO Reading config file: ../main.toml
2020-07-15 13:26:09,998 __main__ INFO Preprocessing
2020-07-15 13:26:10,163 __main__ INFO Creating label masks for pinery-bushfire
2020-07-15 13:26:28,257 __main__ INFO Creating label masks for portugal-wildfire
2020-07-15 13:27:12,841 __main__ INFO Creating label masks for woolsey-fire
2020-07-15 13:27:29,098 __main__ INFO Creating label masks for hurricane-matthew
2020-07-15 13:27:55,095 __main__ INFO Creating label masks for hurricane-harvey
2020-07-15 13:28:42,667 __main__ INFO Creating label masks for nepal-flooding
2020-07-15 13:29:38,395 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 186, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 183, in main
    preprocess(config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 139, in preprocess
    rasterizing(file, (1024, 1024), os.path.join(label_directory, file.split('_')[1] + '.png'), config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 82, in rasterizing
    raster = rasterize([geom], out_shape=[1024, 1024])
  File "/home/wessel/.local/lib/python3.6/site-packages/rasterio/env.py", line 384, in wrapper
    with Env.from_defaults():
  File "/home/wessel/.local/lib/python3.6/site-packages/rasterio/env.py", line 271, in __enter__
    defenv(**self.options)
  File "/home/wessel/.local/lib/python3.6/site-packages/rasterio/env.py", line 310, in defenv
    local._env.start()
  File "rasterio/_env.pyx", line 340, in rasterio._env.GDALEnv.start
  File "rasterio/_env.pyx", line 346, in rasterio._env.GDALEnv.start
  File "/home/wessel/anaconda3/envs/neateo/lib/python3.6/_collections_abc.py", line 664, in __contains__
    def __contains__(self, key):
KeyboardInterrupt
2020-07-15 13:29:46,212 __main__ INFO Reading config file: ../main.toml
2020-07-15 13:29:46,213 __main__ INFO Preprocessing
2020-07-15 13:29:46,384 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 186, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 183, in main
    preprocess(config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 118, in preprocess
    for idx, disaster in tqdm(enumerate(labels_per_disaster.keys()), total = len(labels_per_disaster[disaster])*2):
UnboundLocalError: local variable 'disaster' referenced before assignment
2020-07-15 13:30:15,799 __main__ INFO Reading config file: ../main.toml
2020-07-15 13:30:15,800 __main__ INFO Preprocessing
2020-07-15 13:30:15,965 __main__ INFO Creating label masks for pinery-bushfire
2020-07-15 13:30:35,323 __main__ INFO Creating label masks for portugal-wildfire
2020-07-15 13:31:15,070 __main__ INFO Creating label masks for woolsey-fire
2020-07-15 13:31:29,765 __main__ INFO Creating label masks for hurricane-matthew
2020-07-15 13:31:58,504 __main__ INFO Creating label masks for hurricane-harvey
2020-07-15 13:32:50,601 __main__ INFO Creating label masks for nepal-flooding
2020-07-15 13:33:44,049 __main__ INFO Creating label masks for socal-fire
2020-07-15 13:34:10,561 __main__ INFO Creating label masks for lower-puna-volcano
2020-07-15 13:34:17,072 __main__ INFO Creating label masks for guatemala-volcano
2020-07-15 13:34:18,145 __main__ INFO Creating label masks for hurricane-florence
2020-07-15 13:34:31,216 __main__ INFO Creating label masks for santa-rosa-wildfire
2020-07-15 13:34:53,803 __main__ INFO Creating label masks for hurricane-michael
2020-07-15 13:35:28,330 __main__ INFO Creating label masks for tuscaloosa-tornado
2020-07-15 13:35:49,318 __main__ INFO Creating label masks for moore-tornado
2020-07-15 13:36:18,203 __main__ INFO Creating label masks for mexico-earthquake
2020-07-15 13:37:24,043 __main__ INFO Creating label masks for palu-tsunami
2020-07-15 13:38:22,696 __main__ INFO Creating label masks for joplin-tornado
2020-07-15 13:38:43,447 __main__ INFO Creating label masks for midwest-flooding
2020-07-15 13:39:01,339 __main__ INFO Creating label masks for sunda-tsunami
2020-07-16 11:37:20,089 __main__ INFO Reading config file: ../main.toml
2020-07-16 11:37:20,092 __main__ INFO Preprocessing
2020-07-16 11:37:21,021 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 11:40:41,240 __main__ INFO Reading config file: ../main.toml
2020-07-16 11:40:41,244 __main__ INFO Preprocessing
2020-07-16 11:40:42,145 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 11:41:32,730 __main__ INFO Reading config file: ../main.toml
2020-07-16 11:41:32,734 __main__ INFO Preprocessing
2020-07-16 11:41:33,677 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 11:42:08,978 __main__ INFO Reading config file: ../main.toml
2020-07-16 11:42:08,981 __main__ INFO Preprocessing
2020-07-16 11:42:09,967 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 11:51:52,667 __main__ INFO Reading config file: ../main.toml
2020-07-16 11:51:52,670 __main__ INFO Preprocessing
2020-07-16 11:51:53,596 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 12:00:00,004 __main__ INFO Reading config file: ../main.toml
2020-07-16 12:00:00,006 __main__ INFO Preprocessing
2020-07-16 12:00:00,181 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 12:00:18,455 __main__ INFO Creating label masks for portugal-wildfire
2020-07-16 12:01:02,777 __main__ INFO Creating label masks for woolsey-fire
2020-07-16 12:01:17,052 __main__ INFO Creating label masks for hurricane-matthew
2020-07-16 12:01:41,590 __main__ INFO Creating label masks for hurricane-harvey
2020-07-16 12:02:24,542 __main__ INFO Creating label masks for nepal-flooding
2020-07-16 12:03:17,848 __main__ INFO Creating label masks for socal-fire
2020-07-16 12:03:44,702 __main__ INFO Creating label masks for lower-puna-volcano
2020-07-16 12:03:51,012 __main__ INFO Creating label masks for guatemala-volcano
2020-07-16 12:03:52,142 __main__ INFO Creating label masks for hurricane-florence
2020-07-16 12:04:07,244 __main__ INFO Creating label masks for santa-rosa-wildfire
2020-07-16 12:04:33,267 __main__ INFO Creating label masks for hurricane-michael
2020-07-16 12:05:12,649 __main__ INFO Creating label masks for tuscaloosa-tornado
2020-07-16 12:05:33,849 __main__ INFO Creating label masks for moore-tornado
2020-07-16 12:06:04,762 __main__ INFO Creating label masks for mexico-earthquake
2020-07-16 12:07:07,672 __main__ INFO Creating label masks for palu-tsunami
2020-07-16 12:08:03,025 __main__ INFO Creating label masks for joplin-tornado
2020-07-16 12:08:23,364 __main__ INFO Creating label masks for midwest-flooding
2020-07-16 12:08:40,272 __main__ INFO Creating label masks for sunda-tsunami
2020-07-16 12:08:59,332 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 218, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 215, in main
    create_datapoints(config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 174, in create_datapoints
    with open(root + 'training/key.txt', 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../data/xview/training/key.txt'
2020-07-16 13:20:42,501 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:20:42,502 __main__ INFO Preprocessing
2020-07-16 13:20:42,657 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:20:42,666 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 273, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 269, in main
    create_datapoints(config, args.crop)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 224, in create_datapoints
    os.path.join(label_directory, labels[index].split('_')[1] + '.png'), config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 88, in rasterizing
    result = np.zeros(size)
NameError: name 'size' is not defined
2020-07-16 13:21:26,436 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:21:26,437 __main__ INFO Preprocessing
2020-07-16 13:21:26,593 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:21:26,648 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 273, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 269, in main
    create_datapoints(config, args.crop)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 224, in create_datapoints
    os.path.join(label_directory, labels[index].split('_')[1] + '.png'), config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 121, in rasterizing
    piece.save(dest, optimize=True, transparency=transparency)
UnboundLocalError: local variable 'piece' referenced before assignment
2020-07-16 13:22:00,887 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:22:00,888 __main__ INFO Preprocessing
2020-07-16 13:22:01,051 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:22:01,096 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 273, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 269, in main
    create_datapoints(config, args.crop)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 224, in create_datapoints
    os.path.join(label_directory, labels[index].split('_')[1] + '.png'), config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 102, in rasterizing
    out = Image.new('P', crop_res)
  File "/home/wessel/.local/lib/python3.6/site-packages/PIL/Image.py", line 2593, in new
    _check_size(size)
  File "/home/wessel/.local/lib/python3.6/site-packages/PIL/Image.py", line 2568, in _check_size
    raise ValueError("Size must be a tuple")
ValueError: Size must be a tuple
2020-07-16 13:22:42,404 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:22:42,408 __main__ INFO Preprocessing
2020-07-16 13:22:43,346 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:23:27,674 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:23:27,674 __main__ INFO Preprocessing
2020-07-16 13:23:27,831 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:23:43,230 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/.local/lib/python3.6/site-packages/PIL/ImageFile.py", line 506, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 273, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 269, in main
    create_datapoints(config, args.crop)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 224, in create_datapoints
    os.path.join(label_directory, labels[index].split('_')[1] + '.png'), config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 121, in rasterizing
    out.save(dest, optimize=True, transparency=transparency)
  File "/home/wessel/.local/lib/python3.6/site-packages/PIL/Image.py", line 2158, in save
    save_handler(self, fp, filename)
  File "/home/wessel/.local/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 1284, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/home/wessel/.local/lib/python3.6/site-packages/PIL/ImageFile.py", line 520, in _save
    l, s, d = e.encode(bufsize)
KeyboardInterrupt
2020-07-16 13:28:50,538 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:28:50,538 __main__ INFO Preprocessing
2020-07-16 13:28:50,693 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:28:50,694 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 260, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 256, in main
    create_datapoints(config, args.crop)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 198, in create_datapoints
    image = Image.open(images[index], 'rw')
  File "/home/wessel/.local/lib/python3.6/site-packages/PIL/Image.py", line 2863, in open
    raise ValueError("bad mode %r" % mode)
ValueError: bad mode 'rw'
2020-07-16 13:32:26,185 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:32:26,185 __main__ INFO Preprocessing
2020-07-16 13:32:26,342 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:32:26,347 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 260, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 256, in main
    create_datapoints(config, args.crop)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 199, in create_datapoints
    pieces = crop_image(image, crop_res)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 62, in crop_image
    width, height = crop_res
ValueError: too many values to unpack (expected 2)
2020-07-16 13:32:46,583 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:32:46,586 __main__ INFO Preprocessing
2020-07-16 13:32:47,505 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:33:20,935 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:33:20,938 __main__ INFO Preprocessing
2020-07-16 13:33:21,878 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:37:22,450 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:37:22,451 __main__ INFO Preprocessing
2020-07-16 13:37:22,609 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:37:23,061 __main__ ERROR Uncaught Exception
Traceback (most recent call last):
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 261, in <module>
    main()
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 257, in main
    create_datapoints(config, args.crop)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 211, in create_datapoints
    os.path.join(label_directory, labels[index].split('_')[1] + '.png'), config)
  File "/home/wessel/510/building_detection/neat_eo/preprocess_xview.py", line 95, in rasterizing
    result = np.logical_or(result, raster)
ValueError: operands could not be broadcast together with shapes (512,512) (1024,1024) 
2020-07-16 13:38:17,888 __main__ INFO Reading config file: ../main.toml
2020-07-16 13:38:17,889 __main__ INFO Preprocessing
2020-07-16 13:38:18,056 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 13:52:00,563 __main__ INFO Creating label masks for portugal-wildfire
2020-07-16 14:03:29,271 __main__ INFO Creating label masks for woolsey-fire
2020-07-16 14:08:32,291 __main__ INFO Creating label masks for hurricane-matthew
2020-07-16 14:10:52,249 __main__ INFO Creating label masks for hurricane-harvey
2020-07-16 14:15:14,842 __main__ INFO Creating label masks for nepal-flooding
2020-07-16 14:20:09,614 __main__ INFO Creating label masks for socal-fire
2020-07-16 14:27:41,484 __main__ INFO Creating label masks for lower-puna-volcano
2020-07-16 14:29:40,044 __main__ INFO Creating label masks for guatemala-volcano
2020-07-16 14:29:48,026 __main__ INFO Creating label masks for hurricane-florence
2020-07-16 14:33:12,002 __main__ INFO Creating label masks for santa-rosa-wildfire
2020-07-16 14:35:33,300 __main__ INFO Creating label masks for hurricane-michael
2020-07-16 14:38:55,647 __main__ INFO Creating label masks for tuscaloosa-tornado
2020-07-16 14:41:20,858 __main__ INFO Creating label masks for moore-tornado
2020-07-16 14:43:27,187 __main__ INFO Creating label masks for mexico-earthquake
2020-07-16 14:45:15,127 __main__ INFO Creating label masks for palu-tsunami
2020-07-16 14:47:07,218 __main__ INFO Creating label masks for joplin-tornado
2020-07-16 14:48:21,838 __main__ INFO Creating label masks for midwest-flooding
2020-07-16 14:50:54,092 __main__ INFO Creating label masks for sunda-tsunami
2020-07-16 18:56:53,134 __main__ INFO Reading config file: ../main.toml
2020-07-16 18:56:53,136 __main__ INFO Preprocessing
2020-07-16 18:56:53,357 __main__ INFO Creating label masks for pinery-bushfire
2020-07-16 19:11:27,773 __main__ INFO Creating label masks for portugal-wildfire
2020-07-16 19:25:01,702 __main__ INFO Creating label masks for woolsey-fire
2020-07-16 19:30:58,648 __main__ INFO Creating label masks for hurricane-matthew
2020-07-16 19:34:35,990 __main__ INFO Creating label masks for hurricane-harvey
2020-07-16 19:39:17,915 __main__ INFO Creating label masks for hurricane-florence
2020-07-16 19:43:21,684 __main__ INFO Creating label masks for nepal-flooding
2020-07-16 19:48:06,325 __main__ INFO Creating label masks for socal-fire
2020-07-16 19:57:17,220 __main__ INFO Creating label masks for lower-puna-volcano
2020-07-16 19:59:30,836 __main__ INFO Creating label masks for guatemala-volcano
2020-07-16 19:59:41,889 __main__ INFO Creating label masks for santa-rosa-wildfire
2020-07-16 20:02:42,273 __main__ INFO Creating label masks for hurricane-michael
2020-07-16 20:07:28,196 __main__ INFO Creating label masks for tuscaloosa-tornado
2020-07-16 20:10:15,810 __main__ INFO Creating label masks for moore-tornado
2020-07-16 20:12:26,417 __main__ INFO Creating label masks for mexico-earthquake
2020-07-16 20:14:25,714 __main__ INFO Creating label masks for palu-tsunami
2020-07-16 20:16:49,398 __main__ INFO Creating label masks for joplin-tornado
2020-07-16 20:18:07,820 __main__ INFO Creating label masks for midwest-flooding
2020-07-16 20:21:25,948 __main__ INFO Creating label masks for sunda-tsunami
